name: build
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI: true

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            - uses: bahmutov/npm-install@v1

            - name: check and build
              run: |
                  npm run format:check
                  npm run build
